version: "3"
services:
    carmind-front:
      image: fonzeca/carmind-front:dev
      ports:
        - "3000:3000"
      networks:
        - carmind

networks:
  carmind:
    driver: bridge
    name: carmind
    external: true