version: "3"
services:
    gateway-carmind:
      image: fonzeca/carmind-front:dev
      ports:
        - "80:3000"
      networks:
        - carmind

networks:
  carmind:
    driver: bridge
    name: carmind
    external: true